version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y git python3 python3-pip apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            apt-key fingerprint 0EBFCD88
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            apt update
            apt install -y docker-ce docker-ce-cli containerd.io
      - checkout

      - run:
          name: Push versioned docker containers
          command: |
            aws configure set default.region us-east-2
            aws configure set aws_access_key_id ${AWS_S3_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_S3_SECRET_ACCESS_KEY}
            python/tools/docker/login.sh
            make -C python/tools/docker push-versioned

      # - run:
          # name: Pull docker image
          # command: |
            # set -ex
            # export DOCKER_IMAGE=theh1ghwayman/locobot-assistant:5.0
            # echo Pulling docker image $DOCKER_IMAGE
            # docker pull $DOCKER_IMAGE >/dev/null

workflows:
  build:
    jobs:
      - build
